/**
 * Removes the leading `--` from a CSS custom-property name.
 *
 * @example stripDashes('--is-active') // → 'is-active'
 */
export function stripDashes(paramName: string): string {
  return paramName.replace(/^--/, '');
}

/**
 * Converts a kebab-case string to camelCase.
 *
 * Used to derive the JS property name from a parameter name
 * (after stripping the `--` prefix via {@link stripDashes}).
 *
 * @example kebabToCamel('is-active') // → 'isActive'
 */
export function kebabToCamel(kebab: string): string {
  return kebab.replace(/-([a-z])/g, (_match, ch: string) => ch.toUpperCase());
}

/**
 * Builds the `data-e-<hash>-<param>` attribute name for a state parameter.
 *
 * The attribute is set on the host element at runtime and matched by the
 * CSS selectors generated by the css-emitter.
 *
 * @param hash      Short hash segment extracted from the generated class name.
 * @param paramName Raw parameter name including the `--` prefix (e.g. `--is-active`).
 *
 * @example paramToAttr('a1b2c3', '--is-active') // → 'data-e-a1b2c3-is-active'
 */
export function paramToAttr(hash: string, paramName: string): string {
  const bare = stripDashes(paramName);
  return `data-e-${hash}-${bare}`;
}
